name: Development MLink Analyzer Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'sample-app/**'
      
jobs:
  deploy:
    uses: ./.github/workflows/reuseable-aws-s3-deployment-base.yml
    with:
      app_name: mlink-analyzer
      app_path: sample-app/
    secrets:
      aws_access_key: ${{ secrets.CMNCMP_DEV_S3_DEPLOY_ACCESS_KEY }}
      aws_secret_key: ${{ secrets.CMNCMP_DEV_S3_DEPLOY_SECRET_KEY }}
      s3_bucket: ${{ secrets.CMNCMP_DEV_S3_REACT_APP_DEPLOYMENT_BUCKET }}
      cloudfront_dist_id: ${{ secrets.CMNCMP_DEV_REACT_APP_CLOUDFRONT_DIST }}